# app/version.py
"""Single source of truth for the application version.

``__version__`` is the human-facing release number, bumped by hand. CI writes an
``app/_build_info.py`` (git short SHA + run number) during the Windows build so
every artifact is uniquely identifiable; local/dev runs without that file show
"dev". ``get_version()`` is what the UI and window title display.
"""

__version__ = "1.1.0"


def _build_id() -> str:
    try:
        from app import _build_info  # generated by CI, absent in dev
    except Exception:
        return "dev"
    parts = []
    run = getattr(_build_info, "BUILD_NUMBER", "")
    sha = getattr(_build_info, "BUILD_SHA", "")
    if run:
        parts.append(f"build {run}")
    if sha:
        parts.append(sha)
    return ", ".join(parts) if parts else "dev"


def get_version() -> str:
    """Full display version, e.g. ``1.1.0 (build 42, a1b2c3d)`` or ``1.1.0 (dev)``."""
    return f"{__version__} ({_build_id()})"
